### ISSUE TITLE
error raised while updates the archive

### ISSUE THREAD

**Issue by Guro2** [eglaysher/rldev#4]
I did this in command line
`kprl.exe -a Seen.txt SEEN1101.utf`
it returned
`Fatal error: exception Sys_error("Permission denied")`

There exists a bug fix, but it currently has been deleted from server.

**Comment by eglaysher** [comment]
(I have no idea. I didn't write this and haven't used it in years. I maintain this repository for my own personal archiving purposes.)

**Comment by Guro2** [comment]
All right, this problem has already been solved. Meanwhile I found that Haeleth's rlc was failed to create the archive for newer version of Reallive... and therefore I have to compile your rlc now...
