### ISSUE TITLE
several files missing

### ISSUE THREAD

**Issue by utsukamii** [eglaysher/rldev#6]
the \bin folder that is referenced in \src\install-sh does not exist.
relateldy, none of the .exe files (kprl.exe, rlc.exe, rlxml.exe etc.) are present.

i used to work with this many years ago, so i know they used to exist. what happened?

**Comment by ghost** [comment]
This is a source code repository, so the compiled binaries you speak of are not here. A release with a compiled version can be found in [hiroshil's](https://github.com/hiroshil/rldev) repository.

**Comment by eglaysher** [comment]
As Xerge says, this is a clone of a Haeleth's old source code repository and the binaries were never included in it.
